"""to

Revision ID: 8e6c66c97a0e
Revises: f55b1b33565c
Create Date: 2026-08-21 10:35:42.210774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6c66c97a0e'
down_revision: Union[str, Sequence[str], None] = 'f55b1b33565c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('shopkeeper_name', sa.String(), server_default='xyz', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'shopkeeper_name')
    # ### end Alembic commands ###
