"""total sell column add2

Revision ID: f55b1b33565c
Revises: 
Create Date: 2026-08-21 10:24:38.576503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55b1b33565c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sell', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_product_id'), table_name='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.alter_column('product', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('product', 'sell')
    # ### end Alembic commands ###
